### ISSUE TITLE
HTTP 406 Not Acceptable Errors

### ISSUE THREAD

**Issue by suhaasprasad** [sendgrid/sendgrid-python#149]
I'm seeing a lot of 406 errors being returned recently when trying to send mail. It's strange because I don't see where the "Accepts" header is being added to the requests made by this library, which from my understanding is what would be the cause of an HTTP 406 error.  What's also odd is that it happens non-deterministically, where sometimes the message fails with this 406 error and other times the same message will succeed without issue:

```
SendGridClientError: (406, '<html>\r\n<head><title>406 Not Acceptable</title></head>\r\n<body bgcolor="white">\r\n<center><h1>406 Not Acceptable</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n')
```

**Comment by NickFranceschina** [comment]
we are also seeing these errors recently

**Comment by NickFranceschina** [comment]
we are seeing the same issue

**Comment by afrosimon** [comment]
Same here. We're also using sendgrid-django, for what it's worth.

**Comment by thinkingserious** [comment]
Thanks for the reports! Fixed with: https://github.com/sendgrid/sendgrid-python/releases/tag/v1.5.18

**Comment by NickFranceschina** [comment]
we installed 1.5.18 last evening and still seeing the same problem

SendGridClientError: (406, '<html>\r\n<head><title>406 Not Acceptable</title></head>\r\n<body bgcolor="white">\r\n<center><h1>406 Not Acceptable</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n')

**Comment by thinkingserious** [comment]
@NickFranceschina looks like we are going to need to dig deeper to figure this one out. 

Here is what we need: Please email support@sendgrid.com and include the specific steps to reproduce (i.e. send X amount of emails, using the following code)

Thanks!

**Comment by cdurieux** [comment]
Same problem here... What is the support issue number for this case ?

**Comment by thinkingserious** [comment]
@cdurieux could you please also submit a detailed ticket? Currently, we can't reproduce this issue. Thanks!

**Comment by gsakkis** [comment]
This is still happening for us after the upgrade. This is on Google App Engine in case it matters.

**Comment by NickFranceschina** [comment]
yes, we are also on Google App Engine.   if I could send specific steps to reliably reproduce it, I would... but as OP stated, it's non-deterministic

**Comment by delikat** [comment]
This is not fixed. It is still failing inconsistently for me on GAE.

**Comment by afrosimon** [comment]
I concur, still the same situation for us. Also on GAE.

**Comment by RahavLussato** [comment]
same here, also on GAE

**Comment by brandonmwest** [comment]
This should be resolved for all GAE users now. Sorry for the trouble.

**Comment by nickdirienzo** [comment]
Thanks for fixing @brandonmwest. Just curious, what ended up being the problem?

**Comment by SanghviChirag** [comment]
Hi,
We are still facing this issue on GAE.

**Comment by SofienM** [comment]
Hi,
We are facing the same issue. Sporadically and in a non deterministic way, we receive 
`HTTPError(<HTTPError 406: 'Not Acceptable'>)`

Some precisions:
- http-python-client version: 3.3.2
- sendgrid: 6.7.0
- First error on Apr 28th also (2021)

And the messages are not sent in our cases !

**Comment by Pixel-Jack** [comment]
Hello 💻 
I have the exact same problem. My config is http-python-client version: 3.3.2, sendgrid: 6.7.0 
And like @SanghviChirag when I retry it by hand it works.

**Comment by jacobg** [comment]
We just had this occur too whneing sending an email with sendgrid python client:
```
Failed to send message with http error status_code=406, reason=Not Acceptable, body=b'<html>\r\n<head><title>406 Not Acceptable</title></head>\r\n<body>\r\n<center><h1>406 Not Acceptable</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n'
```

Our software automatically retried the same exact request 8 seconds later, and it succeeded 202.

**Comment by anaulin** [comment]
We're using sendgrid 6.11.0 and http-python-client 3.3.7 and we began seeing sporadic 406 errors since around February 20th. Similar to previous reports, our requests succeed on retries.
