### ISSUE TITLE
7bit encoding with API v3

### ISSUE THREAD

**Issue by jeffoneill** [sendgrid/sendgrid-python#556]
I'm still dealing with the issue I mentioned [here](https://github.com/sendgrid/sendgrid-python/issues/341).  Basically, some links in emails get modified so that a "." is repeated and thus breaking the link.  I believe the problem is caused by a buggy email server.

From this [Sendgrid page](https://sendgrid.com/docs/Classroom/Build/Format_Content/html_formatting_issues.html) and my own research, it seems that 7bit encoding is more robust than quoted printable encoding.

Is it possible to use 7bit encoding with API v3?

If not, is this possible with another API that would also work on App Engine?  (not sure offhand if SMTP would work on App Engine)

**Comment by thinkingserious** [comment]
I have sent along your feedback to our product team. I will post here when I get a response. Thanks @jeffoneill!

I'm not sure about App Engine support. We do have a [SMTPAPI sdk here](https://github.com/sendgrid/smtpapi-python).

**Comment by jeffoneill** [comment]
I should add that the buggy email server is probably not a Sendgrid one but one of a recipient or somewhere in between...  Not looking to fix the server, but for a workaround to avoid the bug.

**Comment by thinkingserious** [comment]
Hi @jeffoneill,

The double dot issue is now fixed on our side. Please let us know if you see this issue again.

Thanks!

With Best Regards,

Elmer

**Comment by jeffoneill** [comment]
I'm still having this issue.

Isn't this an issue that all users of your API v3 experience?  If so, it seems that support 7bit encoding or something more robust should be very high priority.

**Comment by thinkingserious** [comment]
Hello @jeffoneill,

I thought this issue was resolved. I have not seen any other reports of this issue. Could you please reach back out to our support team to help us get to the bottom of this?

With Best Regards,

Elmer
